<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'contact' => [
        'fname'   => 'firstName',
        'lname'   => 'lastName',
        'email'   => 'email',
        'phone1'  => 'phone',
        'address' => 'address1',
        'city'    => 'city',
        'state'   => 'state',
        'zip'     => 'postalCode',

        // 'custom_fields' => [
        //     'customerID' => 'customerID',
        //     'billToAccountID' => 'billToAccountID',
        //     'officeID' => 'officeID',
        //     'companyName' => 'companyName',
        //     'spouse' => 'spouse',
        //     'commercialAccount' => 'commercialAccount',
        //     'status' => 'status',
        //     'statusText' => 'statusText',
        //     'ext1' => 'ext1',
        //     'phone2' => 'phone2',
        //     'ext2' => 'ext2',
        //     'billingCompanyName' => 'billingCompanyName',
        //     'billingFName' => 'billingFName',
        //     'billingLName' => 'billingLName',
        //     'billingCountryID' => 'billingCountryID',
        //     'billingAddress' => 'billingAddress',
        //     'billingCity' => 'billingCity',
        //     'billingState' => 'billingState',
        //     'billingZip' => 'billingZip',
        //     'billingPhone' => 'billingPhone',
        //     'billingEmail' => 'billingEmail',
        //     'lat' => 'lat',
        //     'lng' => 'lng',
        //     'squareFeet' => 'squareFeet',
        //     'lotSize' => 'lotSize',
        //     'addedByID' => 'addedByID',
        //     'dateAdded' => 'dateAdded',
        //     'dateCancelled' => 'dateCancelled',
        //     'dateUpdated' => 'dateUpdated',
        //     'sourceID' => 'sourceID',
        //     'source' => 'source',
        //     'aPay' => 'aPay',
        //     'preferredTechID' => 'preferredTechID',
        //     'paidInFull' => 'paidInFull',
        //     'subscriptionIDs' => 'subscriptionIDs',
        //     'balance' => 'balance',
        //     'balanceAge' => 'balanceAge',
        //     'responsibleBalance' => 'responsibleBalance',
        //     'responsibleBalanceAge' => 'responsibleBalanceAge',
        //     'customerLink' => 'customerLink',
        //     'customerNumber' => 'customerNumber',
        //     'masterAccount' => 'masterAccount',
        //     'preferredBillingDate' => 'preferredBillingDate',
        //     'paymentHoldDate' => 'paymentHoldDate',
        //     'mostRecentCreditCardLastFour' => 'mostRecentCreditCardLastFour',
        //     'mostRecentCreditCardExpirationDate' => 'mostRecentCreditCardExpirationDate',
        //     'regionID' => 'regionID',
        //     'mapCode' => 'mapCode',
        //     'mapPage' => 'mapPage',
        //     'specialScheduling' => 'specialScheduling',
        //     'taxRate' => 'taxRate',
        //     'stateTax' => 'stateTax',
        //     'cityTax' => 'cityTax',
        //     'countyTax' => 'countyTax',
        //     'districtTax' => 'districtTax',
        //     'districtTax1' => 'districtTax1',
        //     'districtTax2' => 'districtTax2',
        //     'districtTax3' => 'districtTax3',
        //     'districtTax4' => 'districtTax4',
        //     'districtTax5' => 'districtTax5',
        //     'districtCode1' => 'districtCode1',
        //     'districtCode2' => 'districtCode2',
        //     'districtCode3' => 'districtCode3',
        //     'districtCode4' => 'districtCode4',
        //     'districtCode5' => 'districtCode5',
        //     'customTax' => 'customTax',
        //     'zipTaxID' => 'zipTaxID',
        //     'smsReminders' => 'smsReminders',
        //     'phoneReminders' => 'phoneReminders',
        //     'emailReminders' => 'emailReminders',
        //     'customerSource' => 'customerSource',
        //     'customerSourceID' => 'customerSourceID',
        //     'customerSubSourceID' => 'customerSubSourceID',
        //     'customerSubSource' => 'customerSubSource',
        //     'maxMonthlyCharge' => 'maxMonthlyCharge',
        //     'county' => 'county',
        //     'useStructures' => 'useStructures',
        //     'isMultiUnit' => 'isMultiUnit',
        //     'autoPayPaymentProfileID' => 'autoPayPaymentProfileID',
        //     'divisionID' => 'divisionID',
        //     'subPropertyTypeID' => 'subPropertyTypeID',
        //     'subPropertyType' => 'subPropertyType',
        //     'agingDate' => 'agingDate',
        //     'responsibleAgingDate' => 'responsibleAgingDate',
        //     'salesmanAPay' => 'salesmanAPay',
        //     'purpleDragon' => 'purpleDragon',
        //     'termiteMonitoring' => 'termiteMonitoring',
        //     'pendingCancel' => 'pendingCancel',
        //     'appointmentIDs' => 'appointmentIDs',
        //     'ticketIDs' => 'ticketIDs',
        //     'paymentIDs' => 'paymentIDs',
        //     'unitIDs' => 'unitIDs',
        // ],
    ],

];
