<?php

if (! function_exists('getTimezones')) {
    function getTimezones()
    {
        return [
            'ACDT'  => 'Australian Central Daylight Time',
            'ACST'  => 'Australian Central Standard Time',
            'ADT'   => 'Atlantic Daylight Time',
            'AEDT'  => 'Australian Eastern Daylight Time',
            'AEST'  => 'Australian Eastern Standard Time',
            'AKDT'  => 'Alaska Daylight Time',
            'AKST'  => 'Alaska Standard Time',
            'AST'   => 'Atlantic Standard Time',
            'AWST'  => 'Australian Western Standard Time',
            'BST'   => 'British Summer Time',
            'CAT'   => 'Central Africa Time',
            'CDT'   => 'Central Daylight Time',
            'CEST'  => 'Central European Summer Time',
            'CET'   => 'Central European Time',
            'CHADT' => 'Chatham Daylight Time',
            'CHAST' => 'Chatham Standard Time',
            'CLST'  => 'Chile Summer Time',
            'CLT'   => 'Chile Standard Time',
            'COT'   => 'Colombia Time',
            'CST'   => 'Central Standard Time (North America)',
            'EAT'   => 'East Africa Time',
            'EDT'   => 'Eastern Daylight Time',
            'EEST'  => 'Eastern European Summer Time',
            'EET'   => 'Eastern European Time',
            'EST'   => 'Eastern Standard Time',
            'GMT'   => 'Greenwich Mean Time',
            'HKT'   => 'Hong Kong Time',
            'HST'   => 'Hawaii Standard Time',
            'ICT'   => 'Indochina Time',
            'IST'   => 'India Standard Time',
            'JST'   => 'Japan Standard Time',
            'KST'   => 'Korea Standard Time',
            'MDT'   => 'Mountain Daylight Time',
            'MSD'   => 'Moscow Daylight Time',
            'MSK'   => 'Moscow Standard Time',
            'MST'   => 'Mountain Standard Time',
            'NZDT'  => 'New Zealand Daylight Time',
            'NZST'  => 'New Zealand Standard Time',
            'PDT'   => 'Pacific Daylight Time',
            'PET'   => 'Peru Time',
            'PKT'   => 'Pakistan Standard Time',
            'PST'   => 'Pacific Standard Time',
            'SAST'  => 'South Africa Standard Time',
            'UTC'   => 'Coordinated Universal Time',
            'WAT'   => 'West Africa Time',
            'WEST'  => 'Western European Summer Time',
            'WET'   => 'Western European Time',
            'WIB'   => 'Western Indonesian Time',
            'WIT'   => 'Eastern Indonesian Time',
            'WITA'  => 'Central Indonesian Time',
        ];
    }
}

if (! function_exists('getTimezoneOffsets')) {
    function getTimezoneOffsets()
    {
        return [
            'ACDT'  => '+10:30',
            'ACST'  => '+09:30',
            'ADT'   => '-03:00',
            'AEDT'  => '+11:00',
            'AEST'  => '+10:00',
            'AKDT'  => '-08:00',
            'AKST'  => '-09:00',
            'AST'   => '-04:00',
            'AWST'  => '+08:00',
            'BST'   => '+01:00',
            'CAT'   => '+02:00',
            'CDT'   => '-05:00',
            'CEST'  => '+02:00',
            'CET'   => '+01:00',
            'CHADT' => '+13:45',
            'CHAST' => '+12:45',
            'CLST'  => '-03:00',
            'CLT'   => '-04:00',
            'COT'   => '-05:00',
            'CST'   => '-06:00',
            'EAT'   => '+03:00',
            'EDT'   => '-04:00',
            'EEST'  => '+03:00',
            'EET'   => '+02:00',
            'EST'   => '-05:00',
            'GMT'   => '+00:00',
            'HKT'   => '+08:00',
            'HST'   => '-10:00',
            'ICT'   => '+07:00',
            'IST'   => '+05:30', // India Standard Time
            'JST'   => '+09:00',
            'KST'   => '+09:00',
            'MDT'   => '-06:00',
            'MSD'   => '+04:00',
            'MSK'   => '+03:00',
            'MST'   => '-07:00',
            'NZDT'  => '+13:00',
            'NZST'  => '+12:00',
            'PDT'   => '-07:00',
            'PET'   => '-05:00',
            'PKT'   => '+05:00',
            'PST'   => '-08:00',
            'SAST'  => '+02:00',
            'UTC'   => '+00:00',
            'WAT'   => '+01:00',
            'WEST'  => '+01:00',
            'WET'   => '+00:00',
            'WIB'   => '+07:00',
            'WITA'  => '+08:00',
            'WIT'   => '+09:00',
        ];
    }
}
